spring:
  application:
    name: notification-service
---
server:
  port: 8081
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_notification_service_cinema_system_microservices_v1
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: hduy09092005@gmail.com
    password: srwmlebtfrsfdxkl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 578
rabbitmq-info:
  topic-exchange-user-notification: TOPIC_EXCHANGE_USER_NOTIFICATION
  routing-key-user-notification: ROUTING_KEY_USER_NOTIFICATION
  queue-name-user-notification: QUEUE_USER_NOTIFICATION