spring:
  application:
    name: booking-service
---
server:
  port: 8085
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_booking_service_cinema_system_microservices_v1
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
#          initial-interval: 3000
---
rabbitmq:
  variable:
    handle-ticket-queue: "QUEUE_HANDLE_SAVES_TICKET_23130075"
    handle-ticket-exchange: "EXCHANGE_HANDLE_TICKET_23130075"
    handle-ticket-routing-key: "ROUTING_KEY_HANDLE_TICKET_23130075"