spring:
  application:
    name: booking-service
---
server:
  port: 8085
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_booking_service_cinema_system_microservices_v1
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
