package com.james.userservice.enums;

public enum HobbyEnum {
  MOVIE_LOVER,
  FILM_ENTHUSIAST,
  CINEPHILE,
  MOVIE_BUFF,
  BINGE_WATCHER,
  SERIES_ADDICT,
  CASUAL_MOVIE_WATCHER,
  STREAMING_FAN,
  THEATER_GOER,
  CINEMA_GOER,
  CLASSIC_MOVIE_FAN,
  HORROR_MOVIE_FAN,
  ACTION_MOVIE_FAN,
  ROMANCE_MOVIE_LOVER,
  SCI_FI_MOVIE_ENTHUSIAST,
  DOCUMENTARY_LOVER,
  ANIMATION_FAN,
}
