spring:
  application:
    name: schedule-service
---
server:
  port: 8084
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_schedule_service_cinema_system_microservices_v1
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
    redis:
      time-to-live: 600000ms