spring:
  application:
    name: schedule-service
---
server:
  port: 8084
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_schedule_service_cinema_system_microservices_v1
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
    redis:
      time-to-live: 600000ms
---
rabbitmq:
  variable:
    movie-schedule-queue: "QUEUE_HANDLE_MOVIE_SCHEDULE_23130075"
    movie-schedule-exchange: "EXCHANGE_HANDLE_MOVIE_SCHEDULE_23130075"
    handle-movie-schedule-routing-key: "ROUTING_KEY_HANDLE_MOVIE_SCHEDULE_23130075"
    save-ticket-queue: "QUEUE_HANDLE_SAVE_TICKET_23130075"
    save-ticket-exchange: "EXCHANGE_HANDLE_SAVE_TICKET_23130075"
    handle-save-ticket-routing-key: "ROUTING_KEY_HANDLE_SAVE_TICKET_23130075"
