spring:
  application:
    name: user-service
---
server:
  port: 8082
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_user_service_cinema_system_microservices_v1
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
cloudinary:
  cloudinary-name: dvynemzxx
  api-key: 368324453129176
  api-secret: FyxpYajXxv58KvfsbG9mYuYWOh8